services:
  - type: web
    name: alphahandle-api2
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r server/requirements.txt
    startCommand: cd server && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
